Added documentation for skip
apeinot/java pull request #28
Opened 2019-02-13 11:12 UTC by francislaus

Added documentation to the function skip in IterImplSkip.java as required by the assignment descritption. This should close #15

2019-02-14 08:52 UTC, Samuelhertzberg requested changes
Typos
" One has to aware that the `default`..." => " One has to be aware that the `default`..."
" There documentation for this function is not existing." =>  The documentation for this function is nonexistent.

2019-02-14 09:26 UTC, apeinot approved these changes
Except from the requested changes, I approve this description

2019-02-14 19:33 UTC, emilelm96 approved these changes

2019-02-15 18:28 UTC, Samuelhertzberg approved these changes

2019-02-15 20:59 UTC, merged