Desc of 'parse'
apeinot/java pull request #34
Opened 2019-02-13 12:58 UTC by Samuelhertzberg

Added a description of the function 'parse' in OmitValue. should resolve #11

2019-02-13 14:23 UTC, francislaus commented
Please close this pull request and open a new one to merge it into the branch 'lab3'

2019-02-13 14:35 UTC, francislaus requested changes
You should add newlines to the first three lines so that it looks good in .md format. The paragraph '!-- What is the purpose of the function --' seems to have some minor spelling mistakes.

2019-02-14 08:50 UTC, francislaus approved these changes
I think it is fine that way

2019-02-14 09:33 UTC, emilelm96 approved these changes

2019-02-14 09:36 UTC, apeinot approved these changes

2019-02-14 09:36 UTC, merged