Added description of updateBindings
apeinot/java pull request #35
Opened 2019-02-13 15:45 UTC by francislaus

Added a description of the updateBindings function, detailing its complexity and purpose.
This should resolve #31

2019-02-14 08:56 UTC, Samuelhertzberg requested changes
"... splitting it into multiple subfunction that change ..." => "... splitting it into multiple subfunctions that change ..."
Well done duderino

2019-02-14 09:38 UTC, emilelmarsson commented
You didn't need to change "a one-liner" to "an one-liner". I think it was correct from the start. Apart from that, it's very good.

2019-02-14 19:34 UTC, emilelm96 approved these changes

2019-02-15 18:28 UTC, Samuelhertzberg approved these changes

2019-02-15 21:05 UTC, merged