Added coverage flags and test for readNumber
apeinot/java pull request #48
Opened 2019-02-14 10:14 UTC by Jonagoo

Added the coverage flags to measure coverage as well as a test to print it for function readNumber in IterImplForStreaming.java
This should resolve #44

2019-02-14 10:26 UTC, Samuelhertzberg commented
Depending on outcome of #42 this will either be approved or changed

2019-02-14 10:30 UTC, Samuelhertzberg requested changes
make changes according to @Jonagoo comment in #42

2019-02-14 11:59 UTC, Samuelhertzberg approved these changes

2019-02-14 12:53 UTC, emilelm96 approved these changes

2019-02-15 11:48 UTC, apeinot approved these changes

2019-02-15 12:00 UTC, merged