Added flags and tests. #24
apeinot/java pull request #49
Opened 2019-02-14 10:41 UTC by emilelmarsson

Now there are flags and coverage checking for createDecoder().

2019-02-14 11:17 UTC, Jonagoo approved these changes

2019-02-14 21:13 UTC, apeinot requested changes
I think you should add two more flags:
- one into the try
- one before the last return of the function

2019-02-14 21:13 UTC, apeinot commented on src/main/java/com/jsoniter/extra/GsonCompatibilityMode.java
>                          String input = iter.readString();
I think you should add flag into the try

2019-02-15 10:38 UTC, francislaus commented
> I think you should add two more flags:
> 
>     * one into the try
> 
>     * one before the last return of the function

I think there should be no flag in the try scope as it is not a branch itself. It gets executed in all cases

2019-02-15 15:16 UTC, emilelmarsson commented
Could we get some confirmation on this, @Samuelhertzberg or @francislaus?

2019-02-15 16:59 UTC, francislaus approved these changes
After further review, I think that it is good as it currently is

2019-02-16 14:41 UTC, Samuelhertzberg commented
What about `iter.readBoolean() ? "true" : "false";` ?

2019-02-16 15:47 UTC, apeinot approved these changes

2019-02-16 16:13 UTC, Samuelhertzberg approved these changes

2019-02-16 18:08 UTC, merged