Add description of chooseImpl in Codegen
apeinot/java pull request #51
Opened 2019-02-14 11:07 UTC by apeinot

Add description of chooseImpl in Codegen
This should resolve #19

2019-02-16 14:18 UTC, emilelmarsson commented
There are some errors in the text which I think you should go over. Some are mere typos, others are errors. For example, sometimes you use the plural form instead of singular, so you just need to add an s. 

One example:
> The chooseImpl() function take**s** this type...

Other times, you forget to use the past tense.

One example:
> In fact, the Type returned by the function is clear while reading the function but the way use**d** to reach...

Other than that, it's good.

2019-02-16 16:15 UTC, Samuelhertzberg requested changes
Change put to but in "....the function throws some exceptions put there is no try/catch."
Otherwise great.

2019-02-16 18:12 UTC, emilelm96 approved these changes

2019-02-17 10:56 UTC, francislaus approved these changes

2019-02-17 13:48 UTC, Samuelhertzberg approved these changes

2019-02-17 14:00 UTC, merged