Add description of readStringSlowPath in IterImpl.java
apeinot/java pull request #60
Opened 2019-02-16 10:27 UTC by apeinot

Complete the report. This is solution of #55

2019-02-16 14:10 UTC, francislaus requested changes
Please read once again over your text to find some small errors. Sometimes, you use a noun in the singular form and miss a 's' at the end of the verb or similar small mistakes (e.g. This strings is stored ...). I did not point them out because I think you will rephrase some things anyway, which would make it redundant to mention every single small mistake. If you want, I can help you, but I think that you have to do some rephrasing first.

2019-02-16 16:30 UTC, Samuelhertzberg approved these changes

2019-02-16 18:13 UTC, emilelm96 approved these changes

2019-02-17 10:45 UTC, francislaus approved these changes

2019-02-17 10:45 UTC, merged