Added refactorimg description of pars() in omitValue.java
apeinot/java pull request #80
Opened 2019-02-17 13:35 UTC by Samuelhertzberg

Added a refactoring description of the method parse(). This is only one of two alternatives. The other being just splitting the function. However I felt that writing two methods would just be to much. Should resolve #29

2019-02-17 15:26 UTC, francislaus requested changes
Good job, but you should change "However there is also smarter ways to acquire the correct string" to "However there **are** also smarter ways to acquire the correct string"

2019-02-17 18:16 UTC, Samuelhertzberg commented
Did a complete rewrite @francislaus

2019-02-18 11:50 UTC, apeinot approved these changes

2019-02-18 12:02 UTC, francislaus approved these changes
Looks good

2019-02-18 12:03 UTC, merged